preferences:
    general:
        audioLib: PTB
        units: deg

window:
    size: [1920, 1080]
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True

monitor:
    name: default
    width: 69.8  # in cm
    distance: 210  # in cm
    gamma: 1

operating system: linux

Task settings: 
    Response interval: 1 # time in s you allow the participant to respond that still counts as correct response (only relevant for unambiguous stimuli)
    Unambiguous trials: 6 # (this is PER unambiguous BLOCK) should be an even nr. to have equally often face and house 
    Blocks: 4 # e.g. 4 blocks would mean 2 rivalry and 2 unambiguous (alternated)
    Stimulus duration rivalry: 20 # 120 (2mins) duration in s
    Break duration: 3 # duration in s
    Stimulus path: './stimuli/'
    Screenshot: False # makes a screenshot when aborting experiment
    Exit key: 'q'
