preferences:
    general:
        audioLib: PTB
        units: deg

window:
    size: [600, 400]
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: False
    winType: pyglet
    waitBlanking: True

monitor:
    name: default
    width: 69.8  # in cm
    distance: 210  # in cm
    gamma: 1

operating system: linux

Task settings: 
    Response interval: 0.8 # time in s you allow the participant to respond that still counts as correct response (only relevant for unambiguous stimuli)
    Unambiguous trials: 10 # total nr of times the stimulus is shown - house OR face (trials = switches + 1)
    Blocks: 4 # e.g. 4 blocks would mean 2 rivalry and 2 unambiguous (alternated)
    Stimulus duration rivalry: 120 # 120 (2mins) duration in s
    Break duration: 3 # duration in s
    Stimulus path: './stimuli/'
    Screenshot: True # makes a screenshot when aborting experiment
