preferences:
    general:
        audioLib: PTB
        units: deg

window:
    size: [1920, 1080]
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True

monitor:
    name: default
    width: 69.8  # in cm
    distance: 198  # in cm
    gamma: 1

operating system: linux

Task settings: 
    Response interval: [0.1, 1.5] # time in s you allow the participant to respond that still counts as correct response (only relevant for unambiguous stimuli)
    Blocks: 4 # e.g. 4 blocks would mean 2 rivalry and 2 unambiguous (alternated)
    Previous percept duration: 5 # in s, mean of percept duration from previous studies (used to determine switches in unambiguos trials)
    Percept duration jitter: 0.1 # in s, added to the previous percept duration (0.1 would be a random UNIFORM jitter between -0.1 and 0.1)
    Stimulus duration rivalry: 20 # 120 (2mins) duration in s
    Break duration: 1 # duration in s
    Nr fading stimuli: 255
    Transition length: 50 # in frames (here I mean screenticks!)
    Stimulus path: './stimuli/'
    Stimulus size: 10 # stimulus size in degrees (INCLUDING FIXATION!)
    Screenshot: False # makes a screenshot when aborting experiment (only use without a subject!!)
    Test stimuli: False
    Exit key: 'q'
    Monitor framerate: 60 # or 120Hz
